name = "importGraph"
defaultTargets = ["ImportGraph", "graph"]
testRunner = "test"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "main"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "nightly-testing"

[[lean_lib]]
name = "ImportGraph"

# `lake exe graph` constructs import graphs in `.dot` or graphical formats.
[[lean_exe]]
name = "graph"
root = "Main"
# Enables the use of the Lean interpreter by the executable (e.g., `runFrontend`) 
# at the expense of increased binary size on Linux.
# Remove this line if you do not need such functionality.
supportInterpreter = true

[[lean_exe]]
name = "test"
srcDir = "scripts"
